### ISSUE TITLE
Is this project dead?  Network interfaces are not displaying.

### ISSUE THREAD

**Issue by cliqer** [PhonePresenter/PhonePresenter#5]
Hi and thank you for this.
Unfortunately It doesn't  work anymore, at least on windows.
Network interface is not recognised and the rest of the process fails.
Can you update it please?

**Comment by chromatical** [comment]
PhonePresenter isn't dead, but I am only fixing critical issues.

Thank you for the report.  I will look into it this weekend and see what I can do.  Everything still seems to be working fine on Linux.

**Comment by cliqer** [comment]
Nice to know 👍 
Cheers buddy

**Comment by chromatical** [comment]
@gianniskarmas It appears that RobotJS in the Windows build got broken somehow.  I have uploaded a rebuilt (and working) version of 2.1.2 that you can get from the releases page.  Thanks again for bringing this to my attention.
